defaults:
- default
train_micro_batch_size_per_gpu: ${hyperparams.batch_size}
gradient_accumulation_steps: ${hyperparams.gradient_accumulation_steps}
optimizer:
    type: ${hyperparams.optimizer.name}
    params:
        lr: 5e-5
        betas: 
            - 0.9
            - 0.999
        eps: 1e-6
        weight_decay: ${hyperparams.optimizer.kwargs.weight_decay}
bf16: 
    enabled: true
zero_optimization: false