model_path_rel: bin/rgb/internvl2-76b-visionenc/
model_path: ${user.working_dir}/${training.rgb_backbone.model_path_rel}

frozen: false
outputs:
  whole: false
  patches: true

projection_dim: ${backbone.hidden_size}

input_size: 448
select_layer: -1
try_to_truncate_layers: true
downsample: True

ema_enabled: ${training.ema_enabled}