defaults:
- action:
  - path
  - steer
- goal:
  - dual_target_point
- reward:
  - reward
- bev: 
  - rgb
- state:
  - speed
- _self_
loss_params:
  default:
    classification: 0
  action: 
    classification: 1
    reconstruction: 1

action_type: ${merge_keys:${training.action}}
state_type: ${merge_keys:${training.state}, ${training.bev}}
non_bev_state_type: ${merge_keys:${training.state}}
bev_type: ${merge_keys:${training.bev}}
goal_type: ${merge_keys:${training.goal}}
reward_type: ${merge_keys:${training.reward}}
condition_on_goal: true
goal_conditioning_type: local
max_token_types: 4
quantized: false

# Data settings
integrate_rewards_to_go: false
context_length: 1
frame_stride: 5
inter_window_stride: 2
skip_noisy: true
trim_first_and_last: true
trim_count: 1
max_instances: -1
drop_last: true
future_horizon: 0
past_horizon: 0
use_future_ego_waypoints: ${has_key:${training.action},waypoints}
use_future_vehicle_forecast: false
forecast_steps: 1
include_noisy_in_action: false
splits:
  train: train
  val: val
dynamic_batching: true # false, whether or not to crop padding
weighted_sampling: false # false, whether or not to sample based on class weights
bucket_weights:
  type: uniform
  total_ratio: 0.6
  weights:
    - 1.0 # general
    - 1.0 # acc_scratch
    - 2.0 # acc_light_pedal
    - 2.0 # acc_medium_pedal
    - 1.0 # acc_heavy_pedal
    - 1.0 # acc_brake
    - 1.0 # acc_coast
    - 3.0 # steer_right
    - 3.0 # steer_left
    - 1.0 # vehicle_hazard_front
    - 1.0 # vehicle_hazard_back
    - 1.0 # vehicle_hazard_side
    - 1.0 # stop_sign
    - 1.0 # red_light
    - 1.0 # swerving
    - 1.0 # pedestrian

get_weight_reduce_fn: mean
get_noisy_reduce_fn: last

# Training settings
split_ratio: 0.8

# Caching
dataset_caching:
  enabled: True
  cache_metadata: True
  cache_slow_attributes: True
  cache_dir: ${cache_dir}
parallel_dataset_init: True
parallel_dataset_workers: 16